version: '2'
services:
  magento_os_graphql_server:
    hostname: graphql-os.test
    container_name: magento_os_graphql_server
    build: containers/apache
    volumes:
        - magento_os_graphql_app_sync:/var/www/html/:nocopy
        - ../shared/.composer:/root/.composer/:cached
    links:
        - magento_os_graphql_mysql:mysql
    environment:
        - DOCKER_FIX=
        - VIRTUAL_HOST=graphql-os.test
        - ENABLE_SENDMAIL=true
        - PHP_IDE_CONFIG="serverName=graphql-os.test"
        - XDEBUG_REMOTE_HOST="${XDEBUG_REMOTE_HOST}"
    ports:
        - 80:80

  magento_os_graphql_mysql:
    container_name: magento_os_graphql_mysql
    image: mysql:5.6
    restart: always
    volumes:
        - ../shared/mysql:/var/lib/mysql:cached
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: db
        MYSQL_USER: root
        MYSQL_PASSWORD: root

volumes:
  magento_os_graphql_app_sync:
    external: true