magento_os_graphql_app:
    container_name: magento_os_graphql_app
    image: busybox
    volumes:
        - ../src:/var/www/html/:cached
        - ../shared/.composer:/root/.composer/:delegated

magento_os_graphql_server:
    hostname: graphql-os.test
    container_name: magento_os_graphql_server
    build: containers/apache
    volumes_from:
        - magento_os_graphql_app
    links:
        - magento_os_graphql_mysql:mysql
    environment:
        - DOCKER_FIX=
        - VIRTUAL_HOST=graphql-os.test
        - ENABLE_SENDMAIL=true
        - PHP_IDE_CONFIG="serverName=graphql-os.test"
        - XDEBUG_REMOTE_HOST="${XDEBUG_REMOTE_HOST}"
    ports:
        - 80:80

magento_os_graphql_mysql:
    container_name: magento_os_graphql_mysql
    image: mysql:5.6
    restart: always
    volumes:
        - ../shared/mysql:/var/lib/mysql:delegated
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: db
        MYSQL_USER: root
        MYSQL_PASSWORD: root
